// <auto-generated />
using System;
using HdHrMonitor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HdHrMonitor.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191027233403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HdHrMonitor.Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Authorization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCIProtection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModulationLock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCRLock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceLock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalQualityDbm")
                        .HasColumnType("int");

                    b.Property<int>("SignalQualityPct")
                        .HasColumnType("int");

                    b.Property<int>("SignalStrengthDbm")
                        .HasColumnType("int");

                    b.Property<int>("SignalStrengthPct")
                        .HasColumnType("int");

                    b.Property<string>("StreamingRateRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SymbolQualityPct")
                        .HasColumnType("int");

                    b.Property<int>("TunerNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
